# config/schema.yaml

dataset:
  path: data/battery_data

target:
  name: rul

group:
  name: battery_id

features:
  numeric:
    - discharge_time
    - max_temp

modeling:
  standardize:
    - discharge_time
    - max_temp
    - rul

bayesian:
  pooled:
    slope: discharge_time

  hierarchical:
    slope: 
      - discharge_time
      - max_temp
    group: battery_id
