# config/schema.yaml

dataset:
  path: data/battery_data

target:
  name: RUL

group:
  name: battery_id

features:
  numeric:
    - discharge_time
    - decrease_in_voltage
    - time_constant_current
    - min_temp
    - max_temp

modeling:
  standardize:
    - discharge_time
    - decrease_in_voltage
    - time_constant_current
    - min_temp
    - max_temp
    - RUL

bayesian:
  pooled:
    slope: discharge_time

  hierarchical:
    slope: 
      - discharge_time
      - max_temp
    group: battery_id
